export const recentProjects = [
    // {
    //     id:1,
    //     title:"SEA SAN Marine Services",
    //     subtitle:"VFD Panel for Yacht Applications",
    //     description:"Supply and programming of Schneider 75KW, single-phase VFD for marine applications with advanced control systems and monitoring capabilities",
    //     usage:"🚢 Marine Industry",
    //     detail1:"75KW",
    //     detail2:"Power Rating",
    //     detail3:"Single Phase",
    //     detail4:"Configuration",
    //     picture:"/yacht-marine-electrical-vfd-control-panel-installa.png"
    // },
    // {
    //     id:2,
    //     title:"Al Khoory Hotels",
    //     subtitle:"Hotel Automation Systems",
    //     description:"VFD panels for hot water systems and biology unit automation panels with smart control integration and energy management",
    //     usage:"🏨 Hospitality",
    //     detail1:"HVAC",
    //     detail2:"Control System",
    //     detail3:"Smart",
    //     detail4:"Integration",
    //     picture:"/hotel-automation-control-panel-for-hvac-and-water-.png"
    // },
    // {
    //     id:3,
    //     title:"Stadium Project",
    //     subtitle:"Power Distribution Systems",
    //     description:"Supply of DB-PMAX systems for major stadium infrastructure project with advanced monitoring capabilities and load management",
    //     usage:"🏟️ Infrastructure",
    //     detail1:"DB-PMAX",
    //     detail2:"System Type",
    //     detail3:"Advanced",
    //     detail4:"Monitoring",
    //     picture:"/industrial-electrical-control-panels-and-automatio.png"
    // },
    {
        id:4,
        title:"Sharjah Municipality",
        subtitle:"Irrigation Control Panel",
        description:"Irrigation Control Panel Systems and Power Distribution Solutions",
        usage:"🏟️ Infrastructure",
        detail1:"135 KW & 95 KW",
        detail2:"Irrigation Panels",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/sharjah-municipality-electrical-project.jpg"
    },
    {
        id:5,
        title:"Sharjah Safari Park - Birdi Project",
        subtitle:"Park Electrical Systems",
        description:"Lighting control panels and automation systems for outdoor park infrastructure",
        usage:"🏟️ Infrastructure",
        detail1:"135 KW & 95 KW",
        detail2:"MCC Panels",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/sharjah-safar-park-birdi-project.jpg"
    },
    {
        id:6,
        title:"Dubai Stadium",
        subtitle:"Lighting Control Systems",
        description:"Advanced lighting control panels for stadium operations and event management",
        usage:"🏟️ Infrastructure",
        detail1:"DB-PMAX",
        detail2:"System Type",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/dubai-stadium-lighting-control.jpg"
    },
    {
        id:7,
        title:"AL NASR SPORTS CLUB",
        subtitle:"VFD Panels Installation",
        description:"Variable Frequency Drive panels for sports facility equipment and systems",
        usage:"🏟️ Infrastructure",
        detail1:"75kw",
        detail2:"VFD Panels",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/al-nasr-sports-club-vfd-panels.jpg"
    },
    {
        id:8,
        title:"Wafi Hotels LLC",
        subtitle:"Al Jaddaf Rotana Hotel",
        description:"Hotel automation and electrical systems for luxury hospitality operations",
        usage:"🏟️ Infrastructure",
        detail1:"Advanced",
        detail2:"Automation",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/wafi-hotels-al-jaddaf-rotana.jpg"
    },
    {
        id:9,
        title:"Wafi Mall Dubai",
        subtitle:"Mall Electrical Infrastructure",
        description:"Large-scale electrical distribution and control systems for commercial mall operations",
        usage:"🏟️ Infrastructure",
        detail1:"LV Panel",
        detail2:"Supply & Installation",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/wafi-mall-dubai-electrical.jpg"
    },
    {
        id:10,
        title:"DUTCO TENNANT LLC",
        subtitle:"Industrial Solutions",
        description:"Custom industrial electrical panels and control systems for manufacturing operations",
        usage:"🏟️ Infrastructure",
        detail1:"DB-PMAX",
        detail2:"Irrigation Panel",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/dutco-tennant-industrial-project.jpg"
    },
    {
        id:11,
        title:"City Walk Dubai",
        subtitle:"Panel Systems & Power Distribution",
        description:"Water Fountain Control Panel Systems and Power Distribution Solutions",
        usage:"🏟️ Infrastructure",
        detail1:"PLC-Based",
        detail2:"Control Panel",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/city-walk-dubai.jpg"
    },
    {
        id:12,
        title:"Salik Dubai",
        subtitle:"Toll System Infrastructure",
        description:"Critical electrical systems and automation panels for toll collection infrastructure",
        usage:"🏟️ Infrastructure",
        detail1:"PLC-based",
        detail2:"ATS Panel",
        detail3:"Advanced",
        detail4:"Monitoring",
        picture:"/salik-dubai.jpg"
    },

]